### ISSUE TITLE
The Object Model of WebsocketClient is counter intuitive

### ISSUE THREAD

**Issue by 13steinj** [danpaquin/coinbasepro-python#137]
Generally websocket APIs have standard implementation of the `on_` functions.

Not only is on_open generally meant to be run after the websocket starts, and not for pre data initialization. Furthermore a soft-private method shouldn't have to be overridden to not connect to the full channel spec by default, especially because with the way the command is sent it's difficult to figure out what the unsubscribe message should be.

I propose that the client be rewritten to be a thin wrapper around websocket-client's WebsocketApplication. All initialization would occur in` __init__`. The API would be similar to Javascripts, and convenience structures would be provided for creating the JSON commands to the websocket API. Most importantly, the socket will not be run on a separate thread.

This is a breaking change, but I'd say it's worth it to give devs an environment that if they've worked with websockets before in other languages, already comfortable with rather than the current counter intuitive and presumptory model.

Assuming this is accepted, I'd be more than happy to write up a PR

**Comment by lirenz** [comment]
dumb question (since I'm not too familiar with the python websocket libraries).

Right now, we seem to be polling via recv(). That implies that we're generally maintaining order - since we look at the websocket buffer -> do an action [which the inheritor defines in on_message()] -> look at buffer again. Would an event-based model maintain order? Or could there be race conditions?

**Comment by 13steinj** [comment]
@lirenz my apologies for not seeing this sooner, I must have accidentally skipped this when markimg my notifications as all read at some point.

Do you mind clarifying what you mean by an event based model?
