### ISSUE TITLE
OrderBook get_current_ticker always returns None

### ISSUE THREAD

**Issue by dude8604** [danpaquin/coinbasepro-python#229]
Code to reproduce problem

`import gdax, time

order_book = gdax.OrderBook(product_id='BTC-USD')
order_book.start()

time.sleep(10)

print(str(order_book.get_current_ticker()))

order_book.close()
`

**Comment by tanaytrivedi** [comment]
Did you pip this library? Currently OrderBook is broken in pip, see #227. You have to install straight from the GitHub.

**Comment by mcardillo55** [comment]
Are you still seeing this issue? I think this may be separate from #227 because in #227, you would get an exception when trying to instantiate OrderBook. Looks more similar to #241, which I believe is just caused by calling get_current_ticker() before the OrderBook is filled. Perhaps we should consider some kind of checking to see if OrderBook is ready?
