### ISSUE TITLE
reinitializing start_t = 0 for ever in websocket_client  _listen

### ISSUE THREAD

**Issue by mcmeyer89** [danpaquin/coinbasepro-python#264]
Hey I'm new her, hope my procedure of reporting is right
i think
start_t = 0
 in line 86 should be mooved outside the while loop

**Comment by mcardillo55** [comment]
I think you're right.

**Comment by royitaqi** [comment]
I think this line is a bug but not the root cause. #256 actually had a good solution, where this line will be removed. Basically the problem is that the `ws.ping` call will be blocked by websocket `recv` method and not called, *even if you guys fix this `start_t = 0` line*. There is a solution in #256 where the ping is moved to a separate thread so that it will not be blocked by `recv`. Although I think it might need some last-mile work to make it gracefully shutdown in the case of `close()` method is called (i.e. user intend to shutdown the client).

**Comment by mcardillo55** [comment]
@royitaqi @deanblacc touches on a few of these issues you're talking about in #271
