### ISSUE TITLE
Message {'message': 'Limit only mode'} when submitting market order?

### ISSUE THREAD

**Issue by jasonmellone** [danpaquin/coinbasepro-python#347]
My code looks like this:
```

submission_res = auth_client.conn.place_market_order(size='5.5',
                                                                          product_id='ETC-USD',side='buy')
```

and has worked flawlessly until recently when I started getting incomplete fills.

For some reason, I am getting back the following message in response to the order above:

> {'message': 'Limit only mode'}

Has anyone else experienced this?

**Comment by noah222** [comment]
Today there was an announcement sent out via coinbase pro status:

_"The following trading books have been moved to limit-only mode
New incident: Resolved
The following trading books have been moved to limit-only mode: BAT-USDC, BCH-BTC, BCH-EUR, BCH-GBP, ETC-BTC, ETC-EUR, ETC-GBP, ETC-USD, ETH-GBP, ETH-USDC, LTC-GBP, ZEC-USDC, ZRX-BTC, ZRX-EUR. Limit orders can be placed and cancelled, and matches may occur. Market orders cannot be submitted. Updates will be posted via Coinbase Pro’s Twitter and Status Page."_

You can subscribe to https://status.pro.coinbase.com/history to get the updates via email. Getting these updates has helped me understand what is going on in situations like this.

What this means is you cannot currently submit a market order and must use a limit order, providing price in order for it to be posted to the order book. I think they do this when the trading volume gets thin or abnormal in order to stabilize the market and prevent chaos.
