### ISSUE TITLE
Websocket provides Incorrect prices

### ISSUE THREAD

**Issue by gegenki** [danpaquin/coinbasepro-python#360]
Simple code looks like this.

```
db = mongo_client.crypto
collection = db.btceur

wsClient = cbpro.WebsocketClient(url="wss://ws-feed.pro.coinbase.com", products="BTC-EUR",
    mongo_collection=collection, should_print=True)

wsClient.start()

s = sched.scheduler(time.time, time.sleep)
def cleanUp(sc):
  nBefore = collection.count_documents({})
  collection.delete_many( {"reason":{ "$ne": "filled"}} )
  nAfter = collection.count_documents({})
  print("Cleanup", "| Before:", nBefore, "| After:", nAfter)
  s.enter(30, 1, cleanUp, (sc,))

s.enter(30, 1, cleanUp, (s,))
s.run()
```

Every 30 seconds it removes anything I don't care about from the database.
Ran it last night and tried to calculate the close price at each minute this morning.
Found some strange values. Checked the log

> {'type': 'received', 'order_id': '23c64a7c-20c2-4ca0-bcd9-18b3b495ad0a', 'order_type': 'limit', 'size': '0.00154797', 'price': '5168.05000000', 'side': 'buy', 'client_oid': '07eb72c0-89aa-409e-b1ef-b4106fd1a740', 'product_id': 'BTC-EUR', 'sequence': 5216764506, 'time': '2019-04-14T01:45:49.441000Z'}
{'type': 'done', 'side': 'buy', 'order_id': '23c64a7c-20c2-4ca0-bcd9-18b3b495ad0a', 'reason': 'filled', 'product_id': 'BTC-EUR', 'price': '5168.05000000', 'remaining_size': '0.00000000', 'sequence': 5216764508, 'time': '2019-04-14T01:45:49.441000Z'}

This shows a BTC-EUR order filled last night at 1:45 UTC for at a price of 5168.05.
The price hasn't been that high since November.
If I check on GDAX, the price at that time was 4505 
<img width="572" alt="Screen Shot 2019-04-14 at 10 11 33" src="https://user-images.githubusercontent.com/406104/56090726-cf29a480-5e9d-11e9-95b1-466a40630591.png">
(Note - time difference is because my computer is in UTC+1)

I have many examples of these supposedly filled trades at wildly inaccurate prices.

**Comment by uclatommy** [comment]
I'm curious to know how you decided this is an error. People could be self-trading or trading bots could be doing all sorts of weird stuff, especially when trade volume is extremely thin. I can imagine that someone could pump prices this way by making small self-trades at higher prices that fill when no one else is trading hoping to hit some trading bot price thresholds in order for them to pile in.

**Comment by noah222** [comment]
For all practical purposes, it's an error if the price found in the feed does not match the price listed on the public chart at a certain time. A difference of information regarding the actual price is confusing for all types of trading analysis and should match across all data-structures, ideally.

I've found the only reliable feed without data corruption is the 'matches' feed. There may be strange bot activity that gets filtered out of it, and that is what coinbase uses for the official published price action. Matches represents and is only allowed to represent completed trades that happens at the prices (on the table) and seems to represent the price value that is good for making trades. Right now I log the matches feed 24/7 and use data with 60 seconds resolution to run backtests. I've found that backtesting with 1 minute candles is also not accurate enough and that I need second-level data in order to properly time the buy and the sell, most of the time. The use bots to 'hide' great trades in the middle of candles. It's a huge amount of data, but then I can be sure what happens live is exactly what happens in the test. Then I can run a live test using the seconds data along with a real live trading session and when the are doing the same thing, you know it is all properly calibrated.

**Comment by noah222** [comment]
> 
> 
> I'm curious to know how you decided this is an error. People could be self-trading or trading bots could be doing all sorts of weird stuff, especially when trade volume is extremely thin. I can imagine that someone could pump prices this way by making small self-trades at higher prices that fill when no one else is trading hoping to hit some trading bot price thresholds in order for them to pile in when they detect the transaction.

I just saw this response and have a question: How would it be possible for someone to self-trade at higher prices than are listed in the order book. In order for your thinking to work, they would have to buy all the sell orders on the book. The price rises as the sell orders are taken out. So just because no trades are executing doesn't mean the price can rise. Most likely, in low liquidity, the price will fall, based on simple rules of supply and demand. Since no demand exists (no one wants to buy) the lowest buy order is significantly below the sell order. So in low liquidity, you expect a quick drop, not a rise.

What would have to happen is that the majority of the orders on the book would be from one player (like coinbase) and they would quickly cancel all of their open sell orders, causing a gap in the book. Then a synchronized system would have to create new buy orders that would be filled at the higher price. This seems possible, but unlikely with Bitcoin.

**Comment by gegenki** [comment]
Looking for 'match' rather than 'filled' does solve the issue for me.

Rather than deleting all the additional data I just wrote it to the database.
Over the same period, many of the fills are at totally different prices to the matches.
I am also interested in what uclatommy means because -  I have no idea what that data is supposed to represent.

**Comment by uclatommy** [comment]
@noah222, I think this is only possible when trading volume is very thin, like what gegenki shows in the graph. You can see that at some periods, there are no trades suggesting that there is a wide buy-sell spread. When no one is trading, I imagine you could create a limit sell at the high end, then a limit buy with the exact same price, and the two orders will match each other. Coinbase defines market orders as maker orders and limit orders as taker orders in their pricing structure, but I'm guessing that distinction is just for pricing. There should be no reason why a limit order cannot match another limit order.

**Comment by mcardillo55** [comment]
Resolved. Closing.
