### ISSUE TITLE
{'message': 'Invalid order_type stop'}

### ISSUE THREAD

**Issue by joseska** [danpaquin/coinbasepro-python#368]
Hi. We have and error when try to make a stop order. the error is:
{'message': 'Invalid order_type stop'}

thanks....

**Comment by noah222** [comment]
Stop orders are no longer supported. You can program it to function that way your self, and still achieve the effect of a stop order that is also a market order. Basically, to do that you would keep track of price, set a threshold yourself and when the condition is satisfied, submit your Market order at that moment. 

I believe this was changed in March.

**Comment by JonasSteur** [comment]
This happens because `stop` isn't a valid order type. The only order types that exist are `limit` and `market`. To create a stop order some extra params need to be send. The test currently in master is failing.

As I just encountered this myself while working on a project that uses this client I will create a PR with a fix.

**Comment by mcardillo55** [comment]
#370 Merged
