### ISSUE TITLE
Authenticated client

### ISSUE THREAD

**Issue by jordinaki** [danpaquin/coinbasepro-python#407]
Hi,

I installed the package, and created a script. No problem with the public client, but no way with the auth client. For example, this code:

import cbpro
key="key"
b64secret="b64secret"
passphrase="passphrase"
auth_client = cbpro.AuthenticatedClient(key, b64secret, passphrase)
auth_client.get_accounts()
print(auth_client.get_accounts())

returns
{'message': 'request timestamp expired'}

Am I doing anything wrong?

Thank you very much for the code and the help!

Jordi

**Comment by lalligagger** [comment]
I am also getting an error
`{'errors': [{'id': 'authentication_error', 'message': 'invalid timestamp'}]}`

**Comment by rfisk961** [comment]
Same Issue with coinbase pro:

get_accounts() throws this error:
{'message': 'request timestamp expired'}

While get_coinbase_accounts() works just fine

**Comment by mtingers** [comment]
I haven't seen this one before myself, but initial thoughts are it's one of these:

1. Have you checked your system's time? Is it correct or has it drifted from the actual date/time?
2. Invalid credentials but misleading response message (except in @nullbutt case).
3. Has the authenticated client been sitting idle for a long time? I glanced at the code and I'm not sure if it refreshes the timestamp for the request header (or if it matters).

**Comment by n45os** [comment]
I'm having this issue even with get_fills()

**Comment by jordinaki** [comment]
My problem was a clock difference. I just changed my clock time so that I get the same clock as coinbase servers:
 auth_client.get_time() # coinbase time
 datetime.datetime.utcnow() # my computer time

I have also seen that my computer's time changes slightly over time, sufficiently to loss synchronization. So every few days I have to synchronize the time again.

**Comment by jordinaki** [comment]
Solved

**Comment by lalligagger** [comment]
Time sync of system time worked for me as well, thanks!

**Comment by gilmotta** [comment]
I would like to contribute to this community. I am running my bot on a Virtualbox VM Windows 10 guest and the ticket I opened #413 is caused by the VM clock drifting from the host clock. I already have plans to improve the VM etc. but before I implement a better environment, I have a python script running in parallel updating the clock every 4 seconds based on a list of Internet Time Servers. Since I implemented this workaround I have not missed one single get_account update. The code I used as the basis for my workaround can be found here:
https://gist.github.com/gilmotta/200dfc135b00b3e97ed79b711de6009a
I hope this helps whoever steps on this mine field that has nothing to do with the coinbasepro libs. The coinbasepro libs run perfectly fine.
