### ISSUE TITLE
Pagination List of List

### ISSUE THREAD

**Issue by Jigsaw-Jams** [danpaquin/coinbasepro-python#64]
Our documentation says that any request involving pagination will return a list of lists. Each list including one page of results.  See `AuthenticatedClient.get_orders()` for an example. Do we actually want this behavior? My first thought while using that method would be to return a single list including all results.

I have made some changes to make these return a single list, and also to remove all of the current pagination helpers and replace them with while loops. You can see the changes on my ["auth-client-cleanup" branch](https://github.com/Jigsaw-Jams/GDAX-Python/commit/4f93726742b7d0b4249017eea6add721b96cff94)

I think that this matches the API spec better, and conforms to our new guiding principles. If you guys agree I will include those changes in my next PR which includes some other fixes and docstrings for AuthenticatedClient.

**Comment by Jigsaw-Jams** [comment]
Oh and in `get_fills(...)` we were using the limit param incorrectly so I modified that to comply with the [API spec](https://docs.gdax.com/#pagination).

> limit	100	Number of results per request. Maximum 100. (default 100)

**Comment by acontry** [comment]
I agree, it makes sense to abstract away pagination through the API. My thought for paginated requests was to allow `before`, `after`, and `limit` parameters to be specified through **kwargs (and to describe these parameters in the docstring so the user knows they're there :) ). That way they're available if needed but don't clutter up the function signature too much.

I actually made very similar changes on my [authorized-client-cleanup](https://github.com/acontry/GDAX-Python/commit/eb4ae4be7e4e7267bd4034c17726c4535549635a) branch. Maybe we can align our changes between our branches to present a unified PR here?

**Comment by Jigsaw-Jams** [comment]
Nice! That is exactly where I was leaning with the`before` `after` and `limit`.

Also I think that we should abstract out all of the other calls to requests into a private method. Something along the lines of`_make_request(self, http_verb, url, params)`. That could internally use a version of `_get_paginated_response()`.

How can we collaborate on a branch prior to submitting a PR?

**Comment by acontry** [comment]
@Jigsaw-Jams That idea sounds good to me. If you don't mind working on my `authorized-client-cleanup` branch, we can collectively push our changes there and then one of us can push the final PR here. Just sent you an invite.

**Comment by bryankaplan** [comment]
Shouldn't we use a generator for pagination? There should be no need to make multiple requests unless the client calls `next()`.

**Comment by Jigsaw-Jams** [comment]
This makes a lot of sense. I was sort of trying to go along with the philosophy of making the methods do exactly what the API docs say, but if we want to go the generator route, I'm not opposed.

**Comment by acontry** [comment]
Using a generator means letting the user handle multiple pages if they want more than 100 results into the past, right? Or is your idea for the generator to grab results added since the last method call? 

I like the idea of abstracting away pagination so the user can simply ask for 300 results and get them, regardless of how many HTTP requests it takes. We can still expose enough options so results can be returned a single page at a time in case that behavior is desired (the use case I can think of is getting as close to real-time processing as possible, but since 

I do like the idea of exposing a way to simply grab the results added since the previous method call. That could be a generator or simply saving a page state for each paginated function in the class object.

**Comment by bryankaplan** [comment]
While I see the usefulness of limits, I'm not convinced that we oughta include it in the pagination logic. If we return a generator, and the client wants only 300 results, they can simply say:

```python
from itertools import takewhile
stuff = takewhile(lambda i: i < 300, client.get_stuff())
```

**Comment by bryankaplan** [comment]
…although I now realize that would be 300 _pages_ of stuff. Maybe it would be good to provide help.

**Comment by bryankaplan** [comment]
Well, no, it wouldn't have to be. We should provide a generator that simply `yield`s each next item in the page, and then fetches the next page as needed. The user would have no visibility into that process, so `takewhile(lambda i: i < 300, client.get_stuff())` should work fine.

**Comment by acontry** [comment]
I've never used `takewhile` before, pretty cool! I also realized that one important use case might be that you have 100,000 fills in your account history and you want to dump them to a DB without holding the entire history in memory - a generator would make that easy.

I'll try to sketch out the use cases for the two proposed APIs here. I haven't used generators very much, so you should correct whatever mess I write :)

**Comment by bryankaplan** [comment]
Yep, you're exactly right about that use case.

Re: sketched out use cases: Sounds good! Thanks @acontry

**Comment by bryankaplan** [comment]
I should point out though that it would be pretty easy to do even without `takewhile`.
```python
i = 0
g = client.get_stuff()
while i < 300:
    try:
        do_something_with(next(g))
    except StopIteration:
        break
```

The question of whether limits are worth including in the library is, I think, ultimately a question of the trade-off between how much complexity it adds versus how much it helps users who may not know how to limit generators. Generally I prefer to give users credit, but if it's just another line or two of code, it really wouldn't bother me.

**Comment by acontry** [comment]
I've spent some time figuring out the dirty details of how this pagination works by playing in the sandbox API. The logic to manage pagination for the user isn't too complicated, but it was tricky to figure out some of the edge cases and understand exactly how `before`/`after` work. Ideally the user shouldn't have to dig into these API details, so I think managing pagination (through generators or otherwise) is worth it.

I have three different scenarios and three different APIs. The first API doesn't manage the cursors at all, so it's up to the user. the second and third ones do manage cursors by maintaining state, but present different interfaces.

### Dump entire fill history (which doesn't fit in memory) to a DB.

**First option**: function returns result and dictionary `page_id` with the current cursor locations. To grab data that happened further in the past, pass `after=page_ids['after']`, and for data that has happened more recently since the last call, use `before=page_ids['before']`.
```python
result, page_ids = client.get_orders(limit_pages=10)
while page_ids['after'] is not None:
    result, page_ids = client.get_orders(limit_pages=10, after=page_ids['after'])
    process_result(result) 
```
**Second option**: client object manages the cursors for the beginning and end of data received. Use `which_orders='older'` to grab data older than the last received data, or `which_orders='newer'` to grab more recent data since last call.
```python
while True:
    result = client.get_orders(limit_pages = 10, which_orders='older')
    if not result:
        break
    process_results(result)
```
**Third option**: `get_orders_gen()` returns a generator to get older and older data, and also a cursor which can later be used to grab more recent data.
```python
order_gen, before = client.get_orders_gen()  # order_gen yields one result at a time
while True:
    try:
        process_result(next(order_gen))
    except StopIteration:
        break
```
### Get 300 most recent orders.
```python
result, page_ids = client.get_orders(limit_pages=3)
```
```python
result = client.get_orders(limit_pages=3)
```
```python
from itertools import takewhile
results = takewhile(lambda i: i < 300, client.get_orders())
```
### Get recent orders. Sometime later, return any orders that have occurred since last call.
```python
result, page_ids = client.get_orders(limit_pages=1) # limit pages so we don't dump full history
# sometime later
result, page_ids = client.get_orders(before=page_ids['before'])
```
```python
result = client.get_orders(limit_pages=1)
# sometime later
result = client.get_orders(which_orders='newer')
```
```python
from itertools import takewhile
order_gen, before = client.get_orders_gen()
results = takewhile(lambda i: i < 100, client.get_orders())
# sometime later
order_gen, before = client.get_orders_gen(before) # feed in `before` so generator stops at data already received
results = [x for x in order_gen]
```

**Comment by bryankaplan** [comment]
What an impressive write-up.

My personal vote is for Option 3, because:
* it makes the elimination of unneeded requests effortless
* It does not attempt to maintain state between calls, which could be problematic if the function is called from more than one place

Does the third option need to `yield (results, before)`? Why not just `results`?

One additional use-case that I think should be documented here is "I just want all of the results." I think ideally `client.get_orders()` should work for all three options. Would it?

**Comment by acontry** [comment]
Thanks for the comments! Now that I've figured out how to use a generator to work cleanly with all our scenarios, I'm on board with going that route. No shared state for the client is a good thing! I added your scenario to the list below, 

### Dump entire fill history (which doesn't fit in memory) to a DB.
```python
order_gen = client.get_orders()  # get_orders() is a generator, yielding one order at a time
while True:
    try:
        process_result(next(order_gen))
    except StopIteration:
        break
```
### Get 300 most recent orders.
```python
from itertools import takewhile
results = takewhile(lambda i: i < 300, client.get_orders())
```
### Get recent orders. Sometime later, return any orders that have occurred since last call.
```python
from itertools import takewhile
order_gen = client.get_orders()
results = takewhile(lambda i: i < 100, client.get_orders())
# For orders, the cursor used is order id number. We save id of the most recent order here.
cursor = results[0]['id'] 
# sometime later
order_gen = client.get_orders(before=cursor) # feed in `before` so generator stops at data already received
results = [x for x in order_gen]
```
### Just give me everything!
```python
results = [x for x in client.get_orders()
```

**Comment by bryankaplan** [comment]
@acontry This is exceptional work. I'm totally on board with it, and I look forward to reading other people's thoughts.

The only thing I have to add is that for the last two scenarios, those list comprehensions can be replaced with `list()`, as in `list(client.get_orders())`. But in most cases it's preferable to avoid reading them all into a list, because that defeats the advantages of using a generator in the first place. If you wanted to process them iteratively, you could say something like:
```python
for order in client.get_orders():
    do_something_with(order)
```
No list required!

**Comment by acontry** [comment]
@bryankaplan  Thanks for the syntax tips! Updated my above post to reflect those suggestions.

**Comment by danpaquin** [comment]
I really like this.  Are there any changes to the repo that may help to make this better for the end user?
